name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true # Crucial for pulling Git LFS files
          fetch-depth: 0

      - name: Build and/or Copy Frontend Files
        run: |
          mkdir staging
          cp -r ide/frontend/* staging/
          # Ensure .nojekyll is in the staging folder
          cp ide/frontend/.nojekyll staging/ || true

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./staging
